
test24_SOURCES := test24.c

hello_SOURCES := hello.c

INSTALL_DIR = $(PREFIX)/bin

helloin.bash_MODE := 755
helloin2.bash_MODE := 755

INSTALLED := hello.bash helloin.bash helloin2.bash

INSTALLED_SRC = $(wildcard $(srcdir)/dogs)

include ./quickbuild.make
